name: cicd flow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Set new version
      run: mvn versions:set -DnewVersion=1.0.${{ github.run_number }}

    - name: Build with Maven
      run: mvn clean install
    
    - name: Get the version number from Maven
      id: get_version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: marco712/springboot-images
        tags: ${{ env.VERSION }}
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Update deployment.yaml
      run: |
        sed -i "s|image: marco712/springboot-images:.*|image: marco712/springboot-images:${{ env.VERSION }}|g" manifests/deployment.yaml

    - name: Commit changes
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Update deployment.yaml with new image version ${{ env.VERSION }}"
        git push

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f manifests/deployment.yaml
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
